### ISSUE TITLE
Criar tela do chat

### ISSUE THREAD

**Issue by giancarloandroid** [giancarloandroid/java-chat-rmi-trabalho#2]
**Descrição**
É preciso criar a tela do chat e efetuar as chamadas das classes que estão no pacote **Cliente**.

**Imagem**
![chat](https://cloud.githubusercontent.com/assets/8602136/20455876/8878a8fe-ae4d-11e6-9b91-ab02b3801249.png)

**Comment by emannuell** [comment]
eu faco
